クラス図初版を作成
yutorisan/RougePuzzle pull request #1
Opened 2022-03-24 14:23 UTC by yutorisan

ゲームルールを基にクラス図作成しました
レビューお願いします

## 設計方針

- クラス同士が直接関係しないように必ずインターフェイスを挟む
- 単一責任原則を遵守

## クラス図説明

- `IRoRxProp<T>`は`IReadOnlyReactiveProperty<T>`のこと
- アイテムやマップピースなどは一部のみ記載
- メソッドやフィールドは必要最低限のもののみ記載  

### Input

- `UnityEngine.Input`から得た情報を`IObservableInputProvider`から発信

### Player

- `PlayerNavigator`はInput情報を受け取って`Player`を動かす
- Playerの各情報は`IReadOnlyPlayer`から読み取り専用で公開
- 後述する`IActor`を実装

### Enemy

- `EnemyNavigator`は`IReadOnlyPlayer`からプレイヤーの行動を読み取ってEnemyの行動を決定
- 同様に`IActor` を実装

### Turn
- `TurnScheduler`は、すべての`IActor`から行動完了通知を受け取る
  - すべての`IActor`が行動完了したらターン終了
- ターンが終了したら、`EventInvoker`が`IMap`の情報を読み取ってイベントを実行する

### Map

- `Map`は`IMapPiece`の集合
-  プレイヤーの位置情報から、そのマスにあるピースのイベントを発火する
  - 例えば、EnemyPieceにいたら`IBattleInvoker`よりバトルフェーズ開始
  - ItemPieceにいたらアイテムを`Use`してアイテム効果発揮
  - StairsPieceにいたら`IFloorMover`からフロア切り替え　など

### Storage

- スコアや残り移動回数などの数値を管理する
- データ編集用インターフェイスと、読み取り専用インターフェイスを分けて用意

### View

- Facadeオブジェクトが読み取り専用インターフェイスから各種情報を持ってくる
- HUDがその情報を基に表示

## 懸念点など

- バトルの仕様が細かく決まっていないため、その部分曖昧な設計になっている
- EnemyとItemが重ならない前提での設計、重なるのであれば設計変更必要かも

2022-03-26 08:47 UTC, uchidas-rogue requested changes
みました。
作業速度に驚嘆しました。

MVPパターンで作成したいので、下記に合わせて変更してほしいです
Model : インターフェイスいる
エンティティのクラス
View用のModelクラス
Service : インターフェイスいる
単体で実行可能な処理をまとめた便利クラス
Veiw : インターフェイスいらない
GameObjectに結びつき、イベントの発火や表示の処理をするクラス
Presenter : インターフェイスいらない
GameObjectに結びつきveiwからのイベントをmodelやserviceなどを用いて処理するクラス

上記の分類でフォルダ分けしてほしいです

2022-03-26 08:48 UTC, uchidas-rogue commented
エンティティはこれに近い感じになると思います
```plantuml
@startuml RougePuzzleEntity

' 0か1	|o--
' 1のみ	||--
' 0以上	}o--
' 1以上	}|--

entity UnitType {
    * Id
    --
    * Name
}

entity Unit {
    * Id
    --
    * UnitTypeId FK
    * Level
    * Exp
    * Position
    * Attack
    * Hp
    * HpMax
    * MapId
    * Xp 
    ' 倒した時に得られる経験点
}

Unit }o-- UnitType

entity ItemType {
    * Id
    --
    * Name
}

entity Item {
    * Id
    --
    * ItemTypeId FK
    * UnitId FK
    * Position
    * Name
    * ObjectId
    * Point
    * EffectTurnNum
}

Item }o-- ItemType
Item }o-- Unit

entity Map {
    * Id
    --
    * row
    * column
    * level
}

entity MapPieceType {
    * Id
    --
    * Name
}

entity MapPiece {
    * Id
    --
    * MapId
    * MapTypeId
}

MapPiece }|-- MapPieceType
MapPiece }|-- Map

entity Score {
    * UnitId FK
    --
    * highscore
    * score
}

Score ||-- Unit

@enduml
```

2022-03-26 08:52 UTC, uchidas-rogue commented
>EnemyとItemが重ならない前提での設計

これは問題ないと思いますが、
現行だと敵と自機が重なったら戦闘のような作りにみえるので、それは問題あると思います

2022-03-26 08:55 UTC, uchidas-rogue commented
> クラス同士が直接関係しないように必ずインターフェイスを挟む

Extenject使うので原則これに賛成ですが、
ViewとPresenterはgameobjectにくっつくてインスタンス生成したいのでインターフェイスなしでよいと思います

2022-03-26 08:58 UTC, uchidas-rogue commented
MVPにするのめんどかったらいってもらったらこのブランチに対して自分の方でプルリクつくるのでおねがいします

2022-03-26 11:49 UTC, yutorisan commented
>MVPにするのめんどかったらいってもらったらこのブランチに対して自分の方でプルリクつくる
すみません、MVPがいまいちわかっておらず
自分が作成したクラス図を基にMVPにするとどんな感じになるのか作ってみてほしいですmm

>現行だと敵と自機が重なったら（周辺８マス？）戦闘のような作りにみえるので、それは微妙かなと思います
これだとまずいでしょうか？どんなのを想像してます？

>ViewとPresenterはgameobjectにくっつくてインスタンス生成したいのでインターフェイスなしでよい
自分がちゃんと理解できてないのかもしれませんが、
PresenterはViewからの情報を基に動作する　＝　PresenterはViewに依存する
ということだと思うので、Viewにはインターフェイスは必要かと思います

2022-03-26 13:24 UTC, uchidas-rogue commented
MVPー＞つくります
敵について
ー＞隣接して殴りあうのかと思ってました。重なってダメージうける感じでしたっけ
presenter,viewのインターフェイス
ー＞mvpだとpresenterはmodelとviewに依存しちゃいます

2022-03-29 13:54 UTC, yutorisan commented
>隣接して殴りあうのかと思ってました
なるほどです
それならEventInvokerの処理でPlayerの周辺８ますを見るようにすれば良いのでおそらく問題ないかと

>インターフェイスについて
多分実物見た方が理解しやすいのでプルリク待ちます！

2022-04-08 10:30 UTC, uchidas-rogue approved these changes

2022-04-10 07:10 UTC, merged